### ISSUE TITLE
Just-install customizer fatal error

### ISSUE THREAD

**Issue by UKayeF** [just-install/just-install#269] opened 2018-07-26 07:46 UTC
REPLACE THIS TEXT WITH A DESCRIPTION OF THE ERROR

Error message:
````
The file https://stable.just-install.it/just-install.exe is not accessible. For this tool to work, please create just-install.exe at the URL https://stable.just-install.it/just-install.exe and reload this page.
````

**Comment by lvillani** [comment] 2018-07-26 17:14
I cannot reproduce this problem.

**Comment by UKayeF** [comment] 2018-08-02 06:43
Me neither. Seemed like this was due to the firewall installed at my workspace.

**Comment by lvillani** [comment] 2018-08-02 07:04
Ok. I'm closing this issue then.

**Closed by lvillani** 2018-08-02 07:04 UTC
