### ISSUE TITLE
Add support for other archive types than .zip

### ISSUE THREAD

**Issue by tlm-2501** [just-install/just-install#293] opened 2019-03-21 11:09 UTC
7zip would be particularly nice to see as I see it being used to distribute some software. I have tried to create a registry entry for MPV for example and instead of it being a simple extraction operation in just-install itself, it ends up becoming something of a nightmare with having to write a custom installation script that would download 7za and extract the archive for me.

**Comment by lvillani** [comment] 2019-03-21 19:08
Duplicate of #241

**Closed by lvillani** 2019-03-21 19:08 UTC
