### ISSUE TITLE
Add the possibility to choose the language of apps to be installed

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install#319] opened 2020-02-28 16:55 UTC
Some apps like Firefox or Thunderbird have a different installer for each language. I don't know if any other app like this exists, but it would be nice if the language could be chosen in J-I.

If accepted, I can write the code for this.

**Comment by lvillani** [comment] 2020-02-28 16:56
Duplicate of #218

**Closed by lvillani** 2020-02-28 16:56 UTC
Labels: duplicate
