### ISSUE TITLE
Gimp installer asking "Install for All Users or Install for me only" on install...

### ISSUE THREAD

**Issue by gregdeichler** [just-install/just-install#340] opened 2020-09-10 19:21 UTC
Hello. Are there any switches available to answer the Gimp installer? When I attempt to install Gimp using "just-install gimp" I get a popup asking "Install for All Users or Install for me only" on install.

Thanks.

**Comment by mimi89999** [comment] 2020-09-10 19:52
I will look into this.

**Comment by mimi89999** [comment] 2020-09-10 21:52
@lvillani We forgot to backport https://github.com/just-install/just-install/commit/91e83e8cba58a80e94050a2f6f8471f6b64f7459 to the latest release. It was in the previous release.

I think that you should either create a stable branch and commit backports there not to forget them or make a new release from master. I'm using https://github.com/just-install/just-install/commit/ecf0d6a3c0d5b5154b742f4d02cf6d41cb352af4 in prod and didn't find any issues yet. I couldn't reproduce this issue on my build.

**Comment by lvillani** [comment] 2020-09-15 15:52
Heh, as soon as I find the time and energy to add missing stuff to the `pkg-registry4` I think we can start stabilising master for the next release. I'll backport the commit above and make a new release for the time being.

**Comment by lvillani** [comment] 2020-09-15 18:38
Should be fixed in v3.4.9

**Closed by lvillani** 2020-09-15 18:38 UTC
