### ISSUE TITLE
Spotify asks normal user account.

### ISSUE THREAD

**Issue by redbaty** [just-install/just-install#242] opened 2017-04-07 17:00 UTC
As the title says, the spotify installation asks to be installed on a normal account, instead of a administrator one

**Comment by geek1011** [comment] 2017-04-07 21:49
You can run just-install as a administrator, and all the installers which it stays will be run as admin as well

**Comment by redbaty** [comment] 2017-04-08 02:41
@geek1011 I'm sorry if I mistook my point, english in no my primary language. The thing is: it's the exact opposite, it won't install if it is being run as a admin. Even if I open a non-admin cmd and run just-install it asks admin rights and it passes forward to the spotify installation wich refuses to install on a admin account. [Here's a pic](http://i.imgur.com/nYQFBAq.jpg)

**Comment by lvillani** [comment] 2017-04-19 16:16
Aw, that's bad. There's no technical reason just-install can't run as a regular user but for some reason unknown to me, Windows insists that an administrator has to run it. Maybe we have to set a flag on the executable at install-time to allow non-privileged users to run it?

**Comment by Schokobecher** [comment] 2017-04-19 18:57
@lvillani I think it's related to the "Installer Detection" used by UAC.
See [here](https://superuser.com/questions/857616/how-to-disable-installer-detection-feature-of-uac-in-windows-7-home-premium)
It's seem to even trip based on file names (Like update.exe, installer.exe) - [Source](http://stackoverflow.com/questions/2222217/exe-name-like-update-exe-blocked-by-uac-in-scheduled-task)

**Comment by redbaty** [comment] 2017-04-25 12:26
Apparently the way chocolatey avoids this is by creating a scheduled task, executing it and deleting the task, so this might be officially incompatible

**Comment by pandanautinspace** [comment] 2017-07-31 17:53
I think that I can confirm that @Schokobecher is correct about tripping on the file name, with just-install.exe renamed to ji.exe, Spotify successfully installs in normal cmd, while just-install.exe elevates itself and spotify install fails.

**Comment by Schokobecher** [comment] 2017-11-16 23:16
So either we have have to rename the project (lolno) or deploy a small helper binary for this?

**Comment by pandanautinspace** [comment] 2017-11-19 01:08
Another thing to try is to add an application manifest to just-install (probably using [rsrc](https://github.com/akavel/rsrc)) with requestedExecutionLevel. According to [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/bb756960.aspx), 
> When the requestedExecutionLevel is present in the embedded application manifest, it overrides Installer Detection.

**Comment by cyagon** [comment] 2018-03-13 17:28
since this problem with the spotify-installer exists since a couple of years now and spotify still didnt fixed it (with an `/admin` parameter for example) im gonna close this issue for now.

**Closed** 2018-03-13 17:28 UTC
